name: Test

on:
  push:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'
  pull_request:
    branches-ignore:
      - gh-pages
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install bundler
      run: npm install -g rollup
    - name: Install dependencies
      run: npm ci
    - name: Bundle
      run: npm run bundle
    - name: Test
      run: npm test
    - name: Speed Test
      run: |
        test/prepare.sh
        npm run speedtest
    - name: Lint
      run: npm run lint
